### ISSUE TITLE
Enhanced Departments pages

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#128]
[This page](http://www.jccmi.edu/about/college-departments-services/) and [this page](http://www.jccmi.edu/academics/academic-departments/) bother me:
1. They are not visually appealing
2. They are completely static (listed items are not dynamically pulled from a central list)
3. They are not consistent with other more elegant list pages like [programs of study](http://www.jccmi.edu/academics/programs-of-study/), [locations](http://www.jccmi.edu/locations/) and even the [staff directory](http://www.jccmi.edu/human-resources/employee-directory/)

I believe these pages could be much easier to manage while at the same time more professional and usable if they followed suit with the other, more developed list pages on the site.

**Comment by banksashleym** [comment]
Totally agree. This was a last minute addition before the site went live because I know a lot of students/employees used this departments tab when it was a main nav link on our old site and I knew I would be flooded with questions on "where did that go?!" I would love to make this a dynamic list and definitely more visually appealing! Right now my goal is checking links and making content updates (now that people are seeing the new site they want to all of a sudden update their content)

After that I am going to start going through the pages and making them look a little nicer..
