### ISSUE TITLE
Ability to customize right sidebars for site sections

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#138]
Could we have the ability to customize the right hand sidebars for specific site sections where we could pull different widget areas?

For instance, we would like the ability to pull just the student life events and have them show up in the right sidebar of the student life section. Also, the alumni section it would be nice to pull in the alumni profiles.

**Comment by joelworsham** [comment]
Got this working. Each site section has 2 available checkboxes in the "Site Section Properties" metabox, "Section Left Sidebar" and "Section Right Sidebar". Checking these enables that sidebar to be unique and customized for any page belonging to that section.

Once you check either of these, if you hop over to the "Widgets" settings page (also available by clicking "Edit Sidebar" when they are checked), you can see the new sidebar area(s). They will be in the format "Section: Section Title" or "Section (right): Section Title".

Two minor caveats currently:

1) You cannot currently edit these from the Customizer.
2) In order to edit these you have to go to the standard "Widgets" page. Once a lot of sections have custom sidebars, this page will become very cluttered. This isn't... bad... more so obnoxious because of the clutter and because of the load time.

I'd like to address both of those sometime, but they aren't stoppers.

You can try this out by switching the theme to the branch `issue/138/section-sidebars`.

**Comment by banksashleym** [comment]
Wow, this is great!! Looks good.

**Comment by banksashleym** [comment]
This seems to no longer work. I created some Phi Theta Kappa events and added it to the category "Phi Theta Kappa." On the Phi Theta Kappa page I enabled the "Section Right Sidebar". In the widgets area, I added the events widget to the "Section (right): Phi Theta Kappa" area but nothing showed up on the page.

Thanks!

**Comment by joelworsham** [comment]
The reason for this is that the only 2 events that exist for Phi Theta Kappa category are drafted. Drafted events are hidden. They need to be published and in the future. I tested by un-drafting it and setting it to the future (on my local site) and it showed up.
