### ISSUE TITLE
Add 5 more events to home page

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/jc-theme-2015#144]

**Comment by d4mation** [comment]
@banksashleym

I saw you commented over on #160, but I decided to solve this over here as this Issue was still Open.

This should be all set to go on the `issue/144/home-page-events-control` branch! If you could pull this onto Staging to confirm, we can get this moved over. The setting for it can be found by editing the Home Page.

![image](https://cloud.githubusercontent.com/assets/7770631/19127643/cfa7d50a-8b0d-11e6-9023-de5511ca1a48.png)

**Comment by banksashleym** [comment]
Thanks! I just tested and changed the theme to the #144 branch. I see the area where I can change the number, and I changed it to 10 but I'm still only seeing 5 events when I update?

**Comment by d4mation** [comment]
I believe I've determined the reason for that.

For my local environment, I've recently pulled down all the data from the LIVE site. However, on Staging, things are a little out of date in comparison to the Live site when it comes to the site content. This means that there actually only are 5 Events on Staging that meet the criteria to show on the Home Page available on Staging so that's what show.

If some more dummy, test Events were added they should show up to whatever value you place there 👍 

You can also test it by putting in a lower value, like 2.

**Comment by banksashleym** [comment]
Oh jeez, I didn't even think about that! This works great, thank you!!

**Comment by d4mation** [comment]
All set on Live!

**Comment by banksashleym** [comment]
Great, thanks so much for your help!
