### ISSUE TITLE
Implement editorial workflow

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#148]
This issue requires lots of definition still. The goal is to develop an automated workflow where users are capable of accessing the content they need to edit and those who have the authority to approve and publish content are the ones with the capability of hitting the publish button. Additionally, we need to ensure that those with the authority to proof and publish are automatically notified when content is pending their approval.

Initially, this will likely be limited to a few user and/or user role relationships and simple email alerts. In the future, we may develop an interface for managing those relationships and may explore developing visual representations of the changes that have been made, activity reports, contextual commenting for editors, support for assignments when multiple proofers exist and other such enhancements.

At this point, we need a clear definition of:

- Who will be authoring content
- Exactly what content will they be authoring
- Who will be responsible for proofing and publishing all of that content (can be different individuals)

Keep in mind that it is always better to think in terms of _roles_ than _users_. So it may be that Ivan the IT Intern authors blog posts and Tina the Technology Trainer publishes them for example. The relationship for this workflow is `IT Intern - > Technology Trainer` and not `Ivan - > Tina`. I hope that makes sense.

**Comment by banksashleym** [comment]
I think for now I would just like the ability for all users that have access to their site section on the live side to be able to save a draft of their changes (without the draft disabled on the live page). So no users on the live side will have publishing rights. They would then send the url links to me (and if I'm not there Marilynn or Dotty) who would be able to publish the pages.

**Comment by brashrebel** [comment]
So on the site we currently have the following roles:

- Forms manager
- Site Section Manager
- Jobs For Jets Manager
- Academics Manager
- Subscriber
- Contributor
- Author
- Editor
- Administrator

Which of the above roles does this apply to? I recommend looking at the users and their roles [here](https://www.jccmi.edu/wp-admin/users.php) and making sure they are all correct before deciding.

So for now, the feature will be very simple. Users with the roles you specify based on my previous question, will have the capability of only authoring content and setting it to "draft" (when they're still working on it) and "pending" when it is ready for review.

When any content is marked as "pending", a specific set of users will be emailed with a link to the edit screen. This group could either be all users with a specific role, or a set of users selected in a new setting we create.

How's that sound? There will be lots and lots of opportunities for improvement afterwards but we're acknowledging now that the initial scope is very limited.

**Comment by banksashleym** [comment]
Could we do just the Site Section Managers? Other than administrator (Marilynn and I) all of the other users are either site section managers or forms managers. And the forms managers basically just log in and download their forms results.

**Comment by joelworsham** [comment]
All set. Here's the flowchart this was based off for reference.
[Editorial Workflow.pdf](https://github.com/JacksonCollege/jc-theme-2015/files/411592/Editorial.Workflow.pdf)

**Comment by banksashleym** [comment]
This looks good to me!

**Comment by banksashleym** [comment]
Sorry, I wanted to check one more thing out for this, but the ability to switch themes is gone? Here is what I get when I view the theme details:
![homepage2](https://cloud.githubusercontent.com/assets/15264315/17977303/31184852-6abf-11e6-8891-45a2ddab9d66.jpg)

**Comment by joelworsham** [comment]
Ah yes, I'm guessing you switched it to "master"? "master" was not yet setup to work with this system.

I've just updated it now and it works.

**Comment by banksashleym** [comment]
Thanks! The only addition that I would suggest is to still have the ability to have the user save the page as a draft? There are many users that create pages and then go back and add content multiple times before they would submit the changes to me. Although now that I'm thinking about it, would saving it as a draft take the page out of commission on the live side? Would there be a way to save it on their end so they can go back to it without sending it to me, and then have be able to "submit for review" when they are done making changes?

**Comment by banksashleym** [comment]
This is perfect, thank you.

**Comment by banksashleym** [comment]
I just notified our developers that they will no longer have publishing rights once these changes go live, but there are three people in IT that posts when there is an unexpected outage with one of our third party programs in the IT area of the site. This mainly happens during the evening hours or on the weekends when she needs to post this information to the IT section. Because of this new process she would have to wait until I approved the page.

With that being said. Would it be a lot of work to almost duplicate the site section manager (one with the ability to go through the proofing process) and then another identical site section manager role how we have it now where they would have publishing rights? Or if there is another way to do it where I can give publishing rights to a select few people in the site section manager role?

Gah, sorry I didn't think about this earlier. This doesn't have to affect the rolling out of the changes, but if it's something we could incorporate I would certainly appreciate it!

**Comment by joelworsham** [comment]
No worries. So, just to clarify, you're asking for a role that only has access to specified sections, but does not have to wait for approval to publish, right?

**Comment by banksashleym** [comment]
Yes, that's correct! For instance, there are a few users in IT who are site section managers for IT and I would like to have them go through the editing process. But Kelly in IT is also a site section manager for IT, but I would specifically like to give her publishing rights because she would need to make the changes live over the weekend.

So basically I would like the option to give a user who is a site section manager publishing rights to their section, but the majority of the users will still go through the editing process (which I LOVE by the way!)

**Comment by joelworsham** [comment]
Okay great, thanks for the clarification. So, how would you feel about me creating a role, identical to Site Section Manager, called "Site Section Publisher" (or something), and the only difference would be that the publisher would have publishing rights. You can very easily swap roles around, so  if you needed to give a site section manager publishing rites briefly, you could swap their role, and then swap back when needed.

**Comment by banksashleym** [comment]
I think that sounds fantastic!

**Comment by joelworsham** [comment]
Okay cool. I will implement that.

**Comment by joelworsham** [comment]
See JacksonCollege/jc-user-roles#11
