### ISSUE TITLE
Adjust scaling of images on the home page

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#149]
A number of images on the site's home page have been found to scale in unexpected ways for differing screen sizes. For this issue, we will need some clarification regarding the exact image spaces which are scaling in the wrong way and how they should be adjusted.

**Comment by banksashleym** [comment]
It seems that all of the images on the homepage are flexible in their scaling (spotlight image, news images and spotlight images . If we could just constrain their proportions when scaling that would be great. All banner images on inside pages scale proportionally, and i would like it if all of the home page could do that as well.

**Comment by joelworsham** [comment]
I *really* think this should not be the case for the homepage main slider. It gets wayyyyy to squished for mobile. Here's a side by side of how it is now (forced to 50% of the screen height):
https://i.imgur.com/ZXh1ZiU.png

And how it will be if we constrain proportions:

https://i.imgur.com/ZLxBInC.png

**Comment by banksashleym** [comment]
I see your point. Is there some way to get all of the picture in? One of our board members is in that top graduation photo, and she made a comment that she was cut out of the image when she looked at it on her phone. 

I don't mind that the image gets smaller, it's the Total Commitment to Student Success and the learn more button that doesn't seem to fit? Could we still constrain the proportions of the image, but pop the "Total Commitment to Student Success" and the "learn more" button below the image and get rid of the image dots just for mobile? Kind of like [Clarkson College](http://www.clarksoncollege.edu/) mobile homepage slider how the text pops below the image for mobile?

**Comment by joelworsham** [comment]
Okay, I still recommend a different course of action. Even if this one edge case board member is visible on the phone, it will be so tiny that no one will be able to tell anyways.

The point is that an image that is optimized for a landscape, desktop view, will very rarely look good on a phone.

What about an option of having a completely different image that loads when the screen is small? So every image has 2 versions, this way you can have 100% control over the way it looks?

**Comment by banksashleym** [comment]
Looking at Clarkson College on my phone, the images shrinking proportionately and getting smaller doesn't bother me, they don't seem too tiny - could we stick to how they do it? I'm just trying to eliminate any extra work on our end with having to choose two different images, or having to resize the same image two times. I think we will just have to be aware of which images we are using and making sure they look good sized down.

**Comment by joelworsham** [comment]
Actually, the way Clarkson does it is that the desktop image is partly hidden behind the header, so that it's not too tall, and then at 992px, the same image is shoved down so the top of it is flush with the header, thus being more viewable on mobile. I like this idea, it would work well.

**Comment by d4mation** [comment]
I scooted the image upward like on Clarkson's site and did a quick transparency on the Header like on their site. I'm not sure how well that will work in this case given the layout of some of the images. It works well for Clarkson since most often they are only needing to clip the very top of someone's head off. 

However, I **_do_** like this solution. It just may require changing up the images shown in order to work in the best possible way.

![image](https://cloud.githubusercontent.com/assets/7770631/17447858/022d6a7c-5b1f-11e6-8140-8650ebcc92ee.png)

For Mobile a Hybrid solution seems to work best in order to fit everything on-screen:

![image](https://cloud.githubusercontent.com/assets/7770631/17448140/b2a06034-5b20-11e6-8dd6-aa3af7afada5.png)

A new branch for this has been made so these changes can be easily tested out on Staging 👍

**Comment by banksashleym** [comment]
I like the idea of moving the image behind the header, but in doing that it shifts all of the content up? I really like how the homepage is designed how where you see the large hero image and just the buttons along the bottom "Future Student" "Current Student". With the hero image moved up, you can now see the content in those future students boxes? Could we move forward with this but just make the image content area larger or taller so that pushes the content back down and we keep the design like below?
![homepage](https://cloud.githubusercontent.com/assets/15264315/17976717/aad5c7da-6abc-11e6-9d74-d721000df277.jpg)

**Comment by d4mation** [comment]
Unfortunately that feeds back into the original problem where people get cut off on the sides.

By telling the image to have a larger height, that proportionately scales the whole image and causes content from the sides to get cut off from view.

This was solved on Mobile by making the image shorter which in turn allowed it to proportionately scale to fit the screen.

![image](https://cloud.githubusercontent.com/assets/7770631/17978893/18b1cdf4-6ac6-11e6-857f-329e3d46e161.png)

**Comment by d4mation** [comment]
I think that overall it looks really nice larger with the image shifted up like that, but it will cause the sides of images to be cut off.

I can add these changes to the branch if you'd like so you could take a look yourself.

**Comment by banksashleym** [comment]
Oh, bummer. Since 80% of the users are viewing on desktop, I would keep it the way it is, where the image remains below the header and just the "Future Students" buttons are showing. Could we still proportionately shrink the image (even though it may be small on mobile) and make the "Total Commitment to Student Success" and "Learn More" button jump to the area below the image (like you showed above)? And then get rid of the dots on mobile? 

I'm trusting your expertise, let me know if we are way overthinking this :) Maybe this just means we find pictures better suited for the area and not have relevant content go right up to the edges?

**Comment by banksashleym** [comment]
Sure, that would be great!

**Comment by banksashleym** [comment]
I agree, I do think it looks nice with the large image behind the header. I am going to ask for feedback about this from my department and I will get back to you. Thanks!!

**Comment by d4mation** [comment]
I just added the changes to the Branch. On Staging if you choose this Branch again it should update it to reflect the new changes.

Personally I would recommend choosing different images that don't have content going right up to the edges. 

People on Mobile are (generally) viewing in Portrait and on Desktop people are almost always viewing in Landscape. When you have an image that is very short and long (Like a Slider image on the Homepage) you either have to make it very small to fit the screen (Like this Branch currently does on Mobile) or you have to cut off the sides in order to keep a larger height. This is why Instagram for example only uses Square Images&mdash;They look the same no matter which you're on.

If the images had less subject matter on the far edges, it wouldn't matter as much if they got cropped a bit on Mobile (or Desktop) in order to stylistically make it fit better on the page while still being visible.

No problem! Let me know how it goes.

**Comment by banksashleym** [comment]
Thanks!! As I'm looking at it on my phone (especially in landscape) I'm noticing some gray bars on either side of the image - I'm assuming since we've constrained the proportions? I think the best bet would be to keep the hero images how we have them currently on the site, and then just make sure that the images we choose look good across all platforms. 

BUT :) could we still have the image go behind the header and have only the buttons visible at the bottom? The look of the homepage on desktop view looks awesome! So basically, if we could have it look like this on a desktop:
![home3](https://cloud.githubusercontent.com/assets/15264315/17980590/f3149e70-6acd-11e6-88e5-ac13acc5670f.jpg)
 and then maintain what we currently have for mobile:
![mobile](https://cloud.githubusercontent.com/assets/15264315/17980597/035b6bd8-6ace-11e6-8d89-0270eb56b66e.jpg)
I would be fine with that. Gah, so sorry to be confusing and indecisive!

**Comment by d4mation** [comment]
On the top edge? Ah, that's an oversight after adjusting the height of the Slider Image apparently. 

If it is over to the side, then it is probably due to #162 which should be fixed in that branch.

So, the new style for Desktop and the old/current style for Mobile? We could get that done 👍

**Comment by d4mation** [comment]
Just pushed a change to this Branch. The Mobile version has been reverted to the old/current version and the Desktop version still has the new styling. You will have to choose this Branch again on Staging to update it to reflect this change.

**Comment by banksashleym** [comment]
Awesome! This looks great, thanks!

**Comment by banksashleym** [comment]
Would you be able to give me the dimensions of this new homepage hero image? I am going to compile some images for this new size for when it's pushed over to live. Thanks!

**Comment by d4mation** [comment]
Given what is showing on my computer, it would seem something along the lines of 1440 pixels wide by 455 pixels tall is what you're looking for.

However, I'd treat that as a ratio. So your height should be about 1/3 the size of your width.

The height is the deciding factor with this code when it comes to determining how much is shown on the page (due to the image scaling to fit the space provided), so if the height is larger than 1/3 of the width you have a higher chance of things being cut off at the edges.

You will also want to ensure that no important subject matter is right at the top of the image or else it will get overlapped by the semi-transparent header.

Let me know if that doesn't make sense!

**Comment by d4mation** [comment]
Edited the ratio above. When I was determining the size of the image it got scooted up which changed the height. I've fixed that now.

**Comment by banksashleym** [comment]
Awesome, thank you! That makes perfect sense :)
