### ISSUE TITLE
Implement search results weighting

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#151]
In an effort to improve the relevance of the search results we need to modify the search logic. Currently, the search is not very smart. It does a poor job of returning more relevant results first and sorting them by likelihood of being correct. It also has little regard for the content type so basically if something is deemed as relevant it is included in no seemingly logical order.

To improve this, we will want to examine the factors that make results more appropriate. Are certain types of content typically better? Is the relevance more likely if the keyword is in the title or in some custom field? How important is the publish date? Things like that.

**Comment by banksashleym** [comment]
I think page titles play an important role, but then I think in some cases it would be helpful to have an additional field to type in some keywords? Thoughts on that? I think we have titled most of the pages to literally say what the page is about. So if someone types in "TRiO newsletters" there is a page called "TRiO newsletters" which should show up first. However, there are a lot of pages just called "Frequently asked questions" so in that instance should I re-name the page title to be "Respiratory Care Frequently Asked Questions" or do we incorporate a separate field so that this page shows up when someone searches for "Respiratory Care"? If there is a standard here it would be great to know your thoughts!

Also, if we can put the most weight on the site section landing pages and program landing pages that would be great. Right now when you type in "Human Resources" I would like the first listing to be the general HR landing page, but currently it's the third.

Also, I think we can eliminate the courses from populating the search. For example, when you search for "Nursing" there is a story about Nursing, and then all of the nursing courses that come up, but the Nursing program doesn't come up at all.

**Comment by joelworsham** [comment]
Implemented the plugin "Relevanssi" into the staging site. This plugin drastically improves the search and weights things properly. I also was able to allow keyword indexing. In order to do this, when on a page,

1. Make sure you have the "Custom Fields" metabox enabled, which you can do from "Screen Options" at the top.
2. Add a new custom field with the name "jc_search_keywords".
3. Enter keywords, separated with spaces, in the field.
4. If you test, and they don't seem to be working, you can manually rebuild the search index by going to Settings -> Relevannsi and clicking "Build The Index".

**Comment by banksashleym** [comment]
Wow, this is awesome!!

**Comment by banksashleym** [comment]
Just tried to go into the Relevanssi plugin and this plugin wasn't on the live side. I can certainly download it myself, but wasn't sure if there were any specific setting set. Thanks!

**Comment by d4mation** [comment]
I have implemented it on the Live Side with all the same settings as were on Staging. Now if you follow the instructions @joelworsham laid out, you should be able to add Search Keywords to specific Posts/Pages on the site 👍

**Comment by banksashleym** [comment]
Awesome! I really appreciate it!
