### ISSUE TITLE
List siblings in sidebar for profiles and spotlights

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#154]
When visiting a profile or a spotlight single, currently the left sidebar has almost nothing in it. It should list sibling entries like most other content types on the site do.

**Comment by banksashleym** [comment]
Sounds good to me

**Comment by d4mation** [comment]
We may want to place restrictions on these, especially for the Spotlights in particular.

On the other Content Types with Sibling Entries in the Sidebar, there's only a maximum of maybe 10 entries. For Spotlights and Profiles, there are quite a few and they really add to the length of the page. Maybe those should show "X" Most Recent rather than all Siblings?

![image](https://cloud.githubusercontent.com/assets/7770631/17338785/d0358cee-58b6-11e6-8505-2a07e9056a8c.png)

**Comment by joelworsham** [comment]
I would say limit 10, or even limit inherited from "posts per page" setting under Reading

**Comment by banksashleym** [comment]
This is great! Could we mirror the News section where I could have those left navigation areas be widget areas, just to keep things looking consistent throughout the site? I would like to copy exactly how we have the News section currently, where I can list "recent posts" (a list of the recent spotlights and profiles) as well as the drop down list for archives?

**Comment by d4mation** [comment]
I just added a Widget Area for the Profiles Pages that will show right below the Siblings from this Issue. 

I believe @joelworsham included this for Spotlights over in #153.

**Comment by banksashleym** [comment]
Sorry, as I was reading what I wrote above, I don't think I was clear :) 

Currently, the news section is listed in the widgets area, where I can drag over "archives" and "Recent Posts" for the news section. I see that now there is a Profile widget area, but when I drag in "archives" it shows an archive list of news and not profiles. I think the goal of this issue is to show users that there are more profiles in the profile section and more spotlights in the spotlight section. I would both the profiles and spotlights to function like the news, where I am able to drag over the "archives" and "recent posts" widgets, but then have the profile side nav show the profiles recent posts and profile archives, and in the spotlight section show the spotlight recent posts and spotlight archives. Would this even be possible?

**Comment by d4mation** [comment]
Ah, I see what you're saying. This should be possible. WordPress' default Archive Widget only supports the default Post Type (Which in your case is "News"), so we'd just need to create an alternate one that allows you to choose whichever one you'd like to display.

**Comment by banksashleym** [comment]
Awesome, that would be great! And I did see when I switched branches that Joel did create a Spotlight widget area like you mentioned above.

Thanks so much for all of your help!!

**Comment by d4mation** [comment]
I just pushed a change to this Branch include a new Widget called "Jackson College Archives" which functions the same as the normal Archives Widget with the addition of being able to set whatever Post Type/Content Type you would like. If you leave that at the default setting, it will choose the Content Type of the Page you are viewing currently.

For the News Pages you can continue to use the old one if you'd like, it won't change anything there. I just wanted to ensure some flexibility and backwards compatibility with the way that I handled this :)

This change is only in this Branch right now, but it will work for the Archive page for Profiles over in #152 once everything is moved Live since they will use the same Widget Area once everything is said and done 👍 

Let me know if you have any questions!

**Comment by banksashleym** [comment]
This is perfect, thanks!! 

In the #154 branch I added the Jackson College Archives widget to the "Profile" section and tested out different content types. Everything pulls great except for the actual "profile" content type - that still pulls news information?

**Comment by d4mation** [comment]
For https://jacksoncollege.staging.wpengine.com/profiles/ you will need to use the Branch for #152. However, it won't be possible to see the new Archives Widget that pulls the Profiles Posts until everything gets merged together when this Milestone is completed. The new Widget Area/Sidebar is what is important for this Branch since it will no longer use the one for the "News" pages.

For pages like https://jacksoncollege.staging.wpengine.com/profiles/make-jackson-college-your-home/ you will need the use the Branch for #154. In this Branch, you will be able to see the new Archives Widget since it is a part of that Branch.

**Comment by joelworsham** [comment]
Is this done and ready to be closed?

**Comment by d4mation** [comment]
I had to look back a bit in the commit history, but I believe so:

Merged:
https://github.com/JacksonCollege/jc-theme-2015/commit/d7c06091f8ebb2d836d19d9216f220141fc7bb74

Original commit from above:
https://github.com/JacksonCollege/jc-theme-2015/commit/b3365f348aabf1c2ec43b0159faee3759934a96b
