### ISSUE TITLE
Color options for alerts

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#156]
It has been acknowledged that not all alerts fit well with the current styling. To improve this, we will implement a tool for selecting the color of an alert.

To accomplish this, I propose that we identify several different _types_ of alerts and then determine how those types of alerts should look. That way, the only change for those publishing alerts will be to select which type they are. This will be much better than simply allowing a color to be selected since it will enforce greater consistency and simplify future modifications.

To accomplish this, please define what the types of alerts should be. They could be things like notice, emergency, announcement, etc. Then, for each type, describe the color scheme.

**Comment by banksashleym** [comment]
I like this idea. Let's do a  "emergency notice, weather notice and general notice" 

-  Let's keep the **emergency notice** the bright red color with white text and emergency icon.
-  **Weather Notice** should be text color: #670140 and background color: #ffecbf (with the option of choosing no icon)
-  **General Notice** should be text color: #670140 and background color: #d4d4d4(with the option of choosing no icon)

**Comment by joelworsham** [comment]
All set. To simplify things, there is only one option in "Display" called "Style". This will automatically set the color and the icon. Feel free to mess around with this on the staging site!

Also, we've implemented something new to the staging site for testing. All new features and updates will be done in their on branch, which is just a specific set of code that addresses each specific feature. Each branch will be named based off the issue it deals with. So, for instance, this issue has its own branch in the theme called `issue/156/alert-styles` and in the CPT Alert repository named `issue/PrimaryTheme156/alert-styles`. In order to test the changes in this issue, you need to activate those branches. To do so:

1. Go to the staging site - jacksoncollege.staging.wpengine.com
2. Go to the themes page - jacksoncollege.staging.wpengine.com/wp-admin/themes.php
3. Click on the theme "Jackson College"
4. You will see "Current branch is `develop`. Try another version" (where "develop" is the current branch). Click on "Try another version" to change branches. For this issue, you would click `issue/156/alert-styles`.
5. Click "Install". The theme is now on that branch!
6. Go to the plugins page - jacksoncollege.staging.wpengine.com/wp-admin/plugins.php
7. Scroll until you see the plugin. For this issue, plugin "JC CPT Alert".
8. You will, again, see "Current branch is `develop`, try another branch.", for whatever branch you're on.
9. Click "Try another branch". For this issue you would click `issue/PrimaryTheme156/alert-styles`. The plugin is now on that branch!

The above steps would get you into the correct branch for the theme and for the applicable plugin. Some issues will only have a branch in the theme. Some only in the plugin. Some may even have multiple plugins with applicable branches. It all depends on the nature of the issue. It should mostly be obvious which branches you need to activate, but if I think it's confusing, I will say right in the issue itself what branches to activate. If you ever can't figure it out, feel free to ask in the issue.

This all seems like a lot, but it's quite simple once you learn how and it will really help streamline our testing process.

If you have any questions, feel free to ask!

**Comment by banksashleym** [comment]
This looks great! Could we remove the icons from each style, however? Just trying to keep things as simple as possible.

Thanks!

**Comment by banksashleym** [comment]
Looks good!

**Comment by banksashleym** [comment]
GAH, nevermind on the icons, I realized I had switched branches so I wasn't on the "alert" branch anymore :)

**Comment by banksashleym** [comment]
Looks good!
