### ISSUE TITLE
New FAQ Ordering

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#192]
Is there a way to implement a drag/drop feature to the new FAQ's to adjust their order? There are a lot of times I'm finding that developers are wanting their FAQ's in a certain order so I have to go through and adjust publish times and it's a pain in the butt!

**Comment by joelworsham** [comment]
Mmmm, yes this could get a bit tricky, but it certainly is possible. I will look into it!

**Comment by joelworsham** [comment]
Alright, I've got this working. I added a "Sort" button on the FAQ list page. If you click it, the page reloads showing all FAQs, sorted by the custom order, and they all become draggable. You can drag and drop the order, then click "Save Sorting" to finalize it.

A few notes:

- Due to the fact that most people will be sorting only with their categories, it is advised that you only ever sort by each category individually. In other words, don't sort when you can see all 133 FAQ items on the screen, as it could break their order.
- You may notice the order shown is different than the order when you click "Sort". This is because WordPress sorts the FAQs by title (or publish date? Can't remember right now), not by "custom order". So, that order does not reflect how they will show up on the website. Once you click "Sort" and the page reloads, they will be in the new "custom order".
