### ISSUE TITLE
Accessibility: Invalid WAI-ARIA role, state or property

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#222]
This is the last of the errors on the home page. the slick dot buttons in the lower right of the hero image are giving an error that each button has an invalid aria label? 
`<ul class="slick-dots" style="display: block;" role="tablist">...</ul>`

Suggested fix:
A WAI-ARIA element contains roles, states or properties that are not allowed on this type of element.

Check the W3C specification for "Accessible Rich Internet Applications Suite" (WAI-ARIA) to see what is supported for this type of element.

**Comment by joelworsham** [comment]
I updated Slick Slider (the carousel library) to the latest version, from 1.5.9 to 1.8.1. This seems to have modified the aria labels to what, I'm assuming, is the proper usage. Please check again and let me know! If it is fixed, feel free to close the issue.

(forgot to mark in commit) Fixed in fe03d13

**Comment by joelworsham** [comment]
Could you do me a quick favor and let me know if this passes tests now? Thanks! :)

**Comment by banksashleym** [comment]
Yes, this seems to be fixed - thanks!
