### ISSUE TITLE
Direct link in profile are on homepage

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#234]
Hi Joel,
Since this is our 90th anniversary, Dotty wanted to add a link to the 90th website on our homepage. She decided that she wanted to use the top profile area and put the 90th logo there and have that area directly link to our 90th section of the website (and ultimately the new 90th sub site).

However, the only way we can do that is to create a "profile page" and from that profile page link to the 90th site. Can we have the ability for these profiles to stay how they are with the title/image/description but then change the link text (and maybe make it a button) and link directly to a url and bypassing the profile page? 

We would love for this to be put to the top of the support list as Dotty is anxious to start publicizing the 90 website. Let me know your thoughts! Thanks!

![capture](https://user-images.githubusercontent.com/15264315/36445908-a409f5a0-164d-11e8-8ed4-6e405652e44e.JPG)

**Comment by joelworsham** [comment]
I would say this probably isn't the best idea. That section of the website has been dedicated to Profiles since inception. Nobody will expect anything there except profiles. Potential downsides:

- Users won't even look there if they aren't already interested in Profiles and know they are there.
- Users will be initially confused by the content if they _are_ interested in Profiles and know they are there.

I would advise we modify the home page template to allow a new area for highlighting this. It can be temporary, or re-usable for highlight big items like this. I would envision it as a full-width banner area below the "Demographic Selector" and above the "Events, News, Profiles" area.

Let me know your thoughts!

**Comment by banksashleym** [comment]
I totally agree with this. Before I created this issue, I suggested to Dotty that maybe we do a full width band below the audience tabs and she preferred that we put it in that bottom right corner of the profiles for the year. I will let her know your suggestions. Maybe i will put together a sample in Photoshop to show her what it would look like and she would be more receptive to the idea. Thanks!

**Comment by banksashleym** [comment]
It appears as if I've lost the battle :( Both Marilynn and Dotty would prefer that this top right profile area be used to be the portal to the new 90th site. If you could proceed with the initial request that would be great. If you could move this issue to the top of the list I would appreciate it! Thank you!

**Comment by joelworsham** [comment]
No problem. That's always unfortunate when the voice of reason goes without being heard :( I will get this set tomorrow.

**Comment by banksashleym** [comment]
Thanks :( I'm bummed...I think a small band below the hero image would have been perfect and would have drawn people in because it's so different. Oh well! Thanks for your help :)

**Comment by joelworsham** [comment]
Got this added. Go to the homepage, click edit page, then you should find a new metabox named "90th Anniversary" where you can input the information. Let me know if anything isn't working as anticipated!

**Comment by banksashleym** [comment]
Thanks!
