### ISSUE TITLE
Google Tag Manager

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#251]
Hi Joel,
Here is the code for the Google Tag Manager. Steve had me set up an account if you could please place this on the website.

Thanks!

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NR8RXL7');</script>

**Comment by BigActual** [comment]
Hi Ashley. The Tag Manager code is in two parts. They require addition of the 'noscript' tag too. Here's the whole dealito:

Install Google Tag Manager
Copy the code below and paste it onto every page of your website.
Paste this code as high in the <head> of the page as possible:

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NR8RXL7');</script>
<!-- End Google Tag Manager -->
```

Additionally, paste this code immediately after the opening <body> tag:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NR8RXL7"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

For more information about installing the Google Tag Manager snippet, visit our [Quick Start Guide ](https://developers.google.com/tag-manager/quickstart).

When finished. You can check that it's working by installing the Google Tag Assistant for Chrome. I'm adding the Value, Tag, and Firing Mechanism for Analytics now, in GTM. 

Because of this, when Joel activates the new code, two instances of the Asynchronous code will fire on the page. Joel will have to verify this on activation. If it does, he will deactivate the Asynchronous Google Analytics Code directly applied to the site to keep double entry from occurring. If it doesn't fire correctly, he'll reach out to me and we'll get it locked in correctly.
