### ISSUE TITLE
Tag manager broken link

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#256]
Hello, I ran our broken links checker today and it's saying that the google tag manager link we added recently to all pages is broken? This is the broken link:

`https://www.googletagmanager.com/ns.html?id=GTM-NR8RXL7`

I'm not familiar with tag manager so wasn't sure if this link being broken means anything or if there is something more I should do?

Thanks!

**Comment by joelworsham** [comment]
Ashley,

Just wanted to let you know that we're checking into this today and will fix it and update results here!

**Comment by BigActual** [comment]
I republished the Tag Manager container and all is fine. The data didn't stop flowing at any point. We kept the old code on site during the changeover to Tag Manager. Regardless, I completed that process so that the errors would go away. 

On a positive note, you'll notice that the views are now working for testing and for Master in Analytics. I'll place some filters on Master so that you can see what data looks like without bots and the like.

**Comment by BigActual** [comment]
@banksashleym Would you please verify that you see data in Analytics flowing the way you expect it to? I'll close this issue after hearing back from you.

**Comment by banksashleym** [comment]
Hello, yes the data seems to be working!
