### ISSUE TITLE
Intranet Project

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#260]
Hi Steve,
I just received your voicemail and thought I would create an issue for this project so I could keep track of the conversation!

- Yes, I'm thinking that this could use our new "base" theme that was created for subsites
- I'm thinking that to start out with, the majority of the information that will be housed on the intranet would be employee pdf forms (mileage forms, faculty syllabi templates, payroll entry forms, etc...) and also our employee directory.

Thanks! I am off all next week but I'm looking forward to discussing this project further!

**Comment by joelworsham** [comment]
How would you imagine people would access the restricted content? I see it as 2 possibilities: password protected OR user account based.

The user account system would be more secure, as it would not involve one global password that could easily be compromised.

Let me know your thoughts!

**Comment by banksashleym** [comment]
Yes, I was thinking we could somehow tie into our password system we use here at the College? I'm not really sure how that would work...but it would allow an employee to use their normal username and password that they use for everything else.

**Comment by banksashleym** [comment]
Hello! I was just checking on on the status of the quote for this intranet project?

Also, would you be able to tell me when we will be back to our one hour a week support to work on issues? I was in a webinar yesterday and they release the 2.1 WCAG guidelines for accessibility and there are a few issues I will be adding to our list.

Thanks!

**Comment by banksashleym** [comment]
Thanks! For the intranet - I think we were just waiting on the price adjustment on creating a section of the current site that could be authenticated instead of a whole new subsite? If it's going to be more work we can stick with the original plan. I will let Dotty know and ask her how she wants to proceed.

Sounds good with the hourly time - I will go through the current issues and prioritize them if that's ok?

**Comment by BigActual** [comment]
Certainly. Go right ahead.

RE: the Intranet.  It would actually take longer to create the subpages because it turns the Jackson college main site into a membership site, That could be a really fun set of tools to play within the long run because it creates a paywall where content is only available to members, but the existing solution doesn't require it. As a separate site, it's all or nothing. so there's no configuration of membership tools.

**Comment by banksashleym** [comment]
Also, I have gone through the issues and closed a lot that aren't really relevant anymore. I numbered the ones I would like to focus on if that's ok? I will be adding more accessibility issues as well. Thanks!

**Comment by d4mation** [comment]
@banksashleym Thanks! I have added them to a new Milestone for the week based on the date. That is preferable over changing the Issue Title as it makes it clear what we're working on that week 👍

**Comment by banksashleym** [comment]
Hello! I just wanted to circle back and touch base on the intranet to see where we stand with everything? IT has approved the purchase of the Mini Orange plugin: https://www.miniorange.com/wordpress-single-sign-on-(sso) for the authentication but I haven't heard back on where we stand with implementing this? If you could let me know that would be great - we can either purchase this on our end (if you could provide the specs on what you need) or you can also bill us if you want to purchase on your end?

Also, is there any area where I can start uploading our documents like the pdf forms? The last time I met with Steve he had me to go a different url to access the intranet other than the one listed in my sites in wordpress. Thanks!

**Comment by banksashleym** [comment]
I just talked with Steve about the authentication plugin for our intranet. Could you go to this link https://www.miniorange.com/wordpress-single-sign-on-(sso) and let me know what option I would need to purchase? I will work with our business office to get the credit card and purchase what we would need and then provide the login credentials. Thanks!

**Comment by banksashleym** [comment]
Thank you so much...just one more question - on the form it's asking if we need any technical support for the plugin? We would have to pay $99 for standard support...let me know if this is something you would require? I really appreciate it :)

**Comment by BigActual** [comment]
Ashley, if we need support on this one, I'll talk with you later about it. Leave it out for now.

**Comment by banksashleym** [comment]
Sounds good, thank you! I will get our college credit card and purchase this and supply the login info.

**Comment by banksashleym** [comment]
I was able to get our business office credit card and purchase the plugin. I have uploaded the plugin as well as the license key. Let me know if you need anything else!

[miniorange-saml-20-single-sign-on-multisite.zip](https://github.com/JacksonCollege/jc-theme-2015/files/2837203/miniorange-saml-20-single-sign-on-multisite.zip)
[MiniOrange License Key.txt](https://github.com/JacksonCollege/jc-theme-2015/files/2837204/MiniOrange.License.Key.txt)

**Comment by d4mation** [comment]
@banksashleym 

I deleted the links after downloading them as this is a public repository and anyone could _technically_ get to them 👍

**Comment by banksashleym** [comment]
Thanks Eric!

**Comment by d4mation** [comment]
@banksashleym 

I installed the purchased version of the plugin (which required me to uninstall the one that was already there) so that I could see what kinds of information I would need to request in order to start getting this set up and it looks like I need you to log in again.

Could you do that for me when you get the chance, please? 

https://jacksoncollege.staging.wpengine.com/wp-admin/network/admin.php?page=mo_saml_settings&tab=login

**Comment by banksashleym** [comment]
Sure! I just tried setting up the account. I bought the license for up to 3 subsites/instance and it's saying that I have 5 subsites...If we are using this just for the intranet is there any way to get around this without having to upgrade?

**Comment by banksashleym** [comment]
I deleted the subsite test site as well as the hccap site (that one wasn't developed yet) and it should be logged in now...we will eventually be adding more subsites - will this plugin not work unless we upgrade base on the number of subsites have even if those don't require any authentication?

**Comment by d4mation** [comment]
Under the SSO Settings Tab, it looks like you can enable/disable it on a per-site basis. So if there are subsites where you do not care to have Single Sign-On integration they can be disabled there.

The plugin should continue to work as long as you only have Single Sign-On enabled for a number of subsites that matches up with what your plan allows.

![image](https://user-images.githubusercontent.com/7770631/52968008-f2dadd80-3379-11e9-8a0a-eb1f2df13679.png)

**Comment by banksashleym** [comment]
Perfect, thank you!

**Comment by d4mation** [comment]
I'm circling back around to getting this configured and it looks like there are some configuration steps that your IT Team would need to handle. 

Ideally, I think that setting this up on Staging first to hammer out the finer details may be best, but it also would mean that your IT Team would need to do these steps twice.

Now that Live has a working URL thanks to #278, we could _technically_ configure this once on Live rather than doing so on Staging and then again on Live. 

The steps for configuring the Identity Provider can be found here on Staging: https://jacksoncollege.staging.wpengine.com/wp-admin/network/admin.php?page=mo_saml_settings&tab=config

The steps would be the same for Live, but utilizing some different values. 

It may be worth configuring this for _both Staging and Live anyway_ as that would allow the Single Sign-On to extend to Staging as well in the event that we're working on some additional functionality on the Staging site and people want to/need to log in using this plugin rather than a regular WP Account. 

This will ultimately depend on what you and your IT Team want to do. 👍

**Comment by BigActual** [comment]
I like this idea of setting it up on both.

**Comment by banksashleym** [comment]
Sounds good, I will send this over to Kelly in IT...she does have an account on staging as a site section manager but when I click on the link from her account the plugin/IP Provider details don't show up. I switched her account to admin and she should now be able to update the IP provider. I will let you know when IT has completed their part. Thanks so much!

**Comment by d4mation** [comment]
Once she has the Identity Provider configured on their end, I will need the following information:

1. X.509 certificate
2. SAML Login URL (Single Sign On URL)
3. IdP Entity ID (IdP Issuer)
4. Is Response signed by your IdP?
5. Is Assertion signed by your IdP?

Since this is a Public Repository, this information may need to be shared over email or something else instead as it is sensitive information.

**Comment by BigActual** [comment]
Timeline adjusted to launch on March 27th

**Comment by d4mation** [comment]
@banksashleym 

Has there been any progress on getting the Identity Provider configured for this?

**Comment by banksashleym** [comment]
Yes, I heard back from Kelly, she was out with a sick child last week and Tim, who will be helping her is out this week! She said first thing next week she will be able to get this information. sorry for the hold up.

**Comment by banksashleym** [comment]
I just checked with Kelly in IT and she has completed their portion and the settings should now be configured for the SSO plugin on the staging site. Let me know if you need anything else from them!

**Comment by d4mation** [comment]
Awesome, thanks! I will need the following information:

1. X.509 certificate
2. SAML Login URL (Single Sign On URL)
3. IdP Entity ID (IdP Issuer)
4. Is Response signed by your IdP?
5. Is Assertion signed by your IdP?

[Since this is a Public Repository](#283), this information may need to be shared over email or something else instead as it is sensitive information.

**Comment by d4mation** [comment]
Oh, wait, actually I see that that was all entered by her. One moment while I review our next steps here :+1:

**Comment by d4mation** [comment]
The next step seems to be that someone with an account in your ADFS setup will need to go to [this page](https://jacksoncollege.staging.wpengine.com/wp-admin/network/admin.php?page=mo_saml_settings&tab=save), click "Test Configuration", log in in the resulting window, and provided that succeeds, check this checkbox:

![image](https://user-images.githubusercontent.com/7770631/54688959-07cf9b80-4af5-11e9-8374-5558161cb13f.png)

Since I do not have an account in your ADFS system, I cannot do this step myself. Trying to check that box without first testing the configuration results in an error.

**Comment by banksashleym** [comment]
I tested the configuration and got a test successful screen, however when i check the box i also get an error?
![Capture](https://user-images.githubusercontent.com/15264315/54689365-c390cb00-4af5-11e9-94bd-ae9ae982eee1.JPG)

**Comment by d4mation** [comment]
Hmm, I was afraid of that. I was wondering if it required a user with an ADFS account to initiate it. I'll take a closer look at what could possibly be causing this.

**Comment by d4mation** [comment]
Excellent, I think this is ready to give a proper test then! 

Visiting https://extranet-jccmi-edu.jacksoncollege.staging.wpengine.com/wp-admin will take you to your ADFS login screen. Logging in there should log you in to the Intranet site. If your ADFS login email is different than your WordPress login email, it should create a WordPress account with the `subscriber` Role, as I set that as the default for now. If it is the same, it should just log you in to your Admin account.

Let me know if it works! I cannot test the full process myself unfortunately.

**Comment by banksashleym** [comment]
Awesome, it worked!! It took me right to the admin dashboard. I will start putting in issues as far as styling goes. I am gathering the content on my end and will be populating the pages today and tomorrow. Woo!

**Comment by d4mation** [comment]
Be sure that you're populating Content on the Live site (https://intranet.1.jccmi.edu/wp-admin/) since we don't ever copy from Staging->Live, so any content you add to the Staging site you'd have to re-enter on Live :+1:

I'll leave this Issue open until SSO is configured on the Live site, as it will need to be done there as well.

**Comment by banksashleym** [comment]
Ok great, I was actually going to ask you about that. Sounds good, I will enter everything into the live site. Thank you!

**Comment by d4mation** [comment]
To continue with configuring this on the Live site, you will need to log in using the credentials that the plugin was purchased with again: 
https://www.jccmi.edu/wp-admin/network/admin.php?page=mo_saml_settings

IT will then need to configure Live in the same way as they did for Staging. I don't know if the configuration would be the same; if IT says that it will be, I can just copy the values over. But it may possibly require them to do some additional things on their end. Here's the same URL as before, but for Live:
https://www.jccmi.edu/wp-admin/network/admin.php?page=mo_saml_settings&tab=config

For any users that Log In using the ADFS portal, we can have them automatically assigned a Role on the WP site (Like Author, Editor, Administrator, etc.) based on their Group/Role within ADFS rather than just automatically making them a Subscriber. If there are any particular combinations that would be preferable, set me know and I can get those configured. I do not know the Group/Role names within your ADFS system, so I would need to know their exact names before that can be implemented.

**Comment by banksashleym** [comment]
Great, I have logged in again and asked Kelly if she could configure the Identity Provider for Live.

I think to start out with, can we have anyone that logs in to the intranet just be able to see the site and not have any wordpress rights? I think once it gets rolling we can identify some key people that can make changes but I think the majority of our employees will just be logging in to see the content of the intranet.

**Comment by banksashleym** [comment]
I just talked to Steve about the styling of the intranet and I think I might have caused a little confusion. I guess I didn't realize that moving the navigation to a vertical would cause more work and that it couldn't easily be done. We found a sample intranet design that I think could work with using the base subsite theme instead? This intranet has a black/gray bar at the top, a nav menu with drop down, a header image below that and the body below that...could we tweak the base subsite theme to resemble that structure and styling or would that require a whole new theme? Here is the link to the sample:

http://www.inter-reaction.com/rei/

**Comment by BigActual** [comment]
Ignore that last post. Ashley and I talked one more time and the nav change to vertical is fine. It will be done in the next sprint

**Comment by banksashleym** [comment]
Kelly in IT has input her portion to configure the live side for the SSO plugin. Let me know if you need anything else!

**Comment by d4mation** [comment]
Just enabled this for the Intranet Live Site. You should be able to log in with your ADFS credentials here: https://intranet.1.jccmi.edu/wp-admin/

**Comment by banksashleym** [comment]
It didn't direct me to the screen to put in my credentials, but I could see that it cycled through the page. I'm assuming it's because I have already logged in an it's remembering my credentials? I did clear my history/cache and still didn't ask for my username/password but I tried it in Firefox (when I didn't yesterday) and it did stop at the login page. Thanks!

**Comment by d4mation** [comment]
Yes, if you're logged in already then it won't prompt you. I checked it on my end using an Incognito window to ensure that it didn't think I was already logged in. 👍 

I am going to close this in favor of https://github.com/JacksonCollege/jc-intranet-theme/issues/1 and #290 since those hold more specific tasks.
