### ISSUE TITLE
Plugins/shortcode for multisite

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#279]
Hello! Could you make the plugins and shortcode that were developed for our main JC website active on multisite so that I can utilize them on the subsites as well? Thanks!

Plugins:

- [x] FAQ
- [x] Staff
- [x] Alerts

Shortcode:

- [x] Tabs
- [x] button
- [x] columns

**Comment by d4mation** [comment]
This is now on the Staging Server as an addition to the Jackson College Base Theme. This will allow all of the subsites to utilize them.

To be sure that I understood your request properly, this enables the use of:

- Alerts (When the Alerts CPT Plugin is active)
- The `[archive_staff]` Shortcode (When the Staff CPT Plugin is active)
- The `[archive_faq]` Shortcode (When the FAQ CPT Plugin is active)
- The `[tabs]` Shortcode
- The `[button]` Shortcode
- The `[row]` and `[column]` Shortcode

These components were all copied over from the Main Site's Theme as they are "Display Logic"; that is, they are bits of code for showing things on the Frontend of the site. 

However, unlike Plugins (Which should ideally only ever control Functionality that can be driven from the Backend of the site), this means that if there is some major change made to how these work on the Main Site, we will need to manually bring these changes over to the Subsite Theme because they are two separate Themes and do not directly share code with one another.

**Comment by banksashleym** [comment]
perfect, thank you!

**Comment by d4mation** [comment]
This change has been pushed Live 👍
