### ISSUE TITLE
alerts showing up on search page

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#286]
Hello,
This isn't a huge deal, but I just did an alert on our subway and health clinic pages with the hours for our spring break next week as a pop up. I wanted to test to make sure they were looking ok, so when I went to the website and searched "subway" the alert showed on the search results page. I have it set to just show up on the subway page.

Also, I clicked on "persistent" so that it shows up every time and that doesn't seem to be working either? I close out the browser and then start it again and the alert isn't showing up. 

Thanks!

**Comment by d4mation** [comment]
This was a fairly edge-case condition that you happened to stumble upon! This is due to how WordPress handles Search Pages (and really any list of Pages/Posts) in that when it loops through them, WordPress temporarily considers the current item the Page being viewed. It does this to make some development stuff easier.

Because of this, when the page loaded and checked to see if there were any Alerts, it was actually checking the first result which was the Subway page. The Subway page had Alerts set up for it, so those were being shown. If the Subway page were instead the second result, this bug wouldn't have shown itself.

I've pushed a fix to the Staging site for this. Can you please confirm that the Alert is no longer showing when you're Searching?

**Comment by banksashleym** [comment]
Perfect! The alert is no longer showing when i search.

Is there anything else I can do so that the alert shows up every time a user goes to the page or if it's refreshed? I have the persistent checkbox checked and it still only shows up one time.

**Comment by d4mation** [comment]
I just pushed a fix for this to Staging. When you get the chance, please check it out :+1:

If you've already dismissed the persistent Alert on a page before now, you will need to right-click the page, click "Inspect Element", click the "Console" tab and then paste in the following code and hit "Enter" to clear out the fact that it has been dismissed:

`jc_clear_alert_cookies()`

That will clear out the dismissed status for that Alert in your web browser for any Alerts on that page. 

Note: If you're afraid other users have previously dismissed this persistent Alert and you want to ensure that they start to see it again, the only option would be to delete the Alert and to make a new one, unfortunately :/ That will cause it to have a new ID number and will force it to show for them as it is now a new Alert.

**Comment by banksashleym** [comment]
This is great, thank you!

**Comment by d4mation** [comment]
This change is now Live 👍
