### ISSUE TITLE
search page different formatting

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#287]
Again, not a big deal but wanted to document it :) I noticed that some words I search for have different formatting on the search results page?

For example, if I search for **transcript** the results page looks like it normally does, however if I search for **marketing** it very quickly (almost like a subliminal message) shows a stripped down version of the new contact form and then on the search result page the titles are much smaller.

And now that I seem them like this I really like the size of the smaller version...but not sure what's going on with the quick redirect of the contact form? And it only happens on certain search terms, not all of them. If you could change the CSS to the smaller version that would be great and then just figure out why the contact form shows up for a split second?

Thank you!!

**Comment by d4mation** [comment]
This seems to be caused by a combination of a couple factors:

1. The fix we had to put in place for #268, which causes a lot of scripts on the site to load slightly later than they otherwise would
2. Overall browser and Internet connection speed

I've made some changes to help alleviate this, including using Inline Styling on the Pop-Overs so that they're always hidden by default no matter if the CSS or JavaScript has loaded yet or not.

> And now that I seem them like this I really like the size of the smaller version

On my computer this all happens pretty quickly, so I do not see the smaller version. Even when I intentionally throttle my connection I cannot see the smaller text sizes. Could you get a screenshot of the difference? Maybe I could approximate the difference using that.

These changes are otherwise now on Staging if you could please check that it is working as expected 👍

**Comment by banksashleym** [comment]
Thanks! This seems to be working much better as far as the form not popping in for a split second. The results pages font sizes still look different however? I searched for "transcript" and the title look like the traditional h1 header that they've always looked like:
![big](https://user-images.githubusercontent.com/15264315/54543704-8650ff80-4974-11e9-8cca-431556fec8c0.JPG)
But if I search for "marketing" titles of the pages in the search results page seem much smaller than an H1? I do like this smaller size if we can just make all the results have this formatting? Not sure why different search terms would result in different formatting on the search results page though?
![small](https://user-images.githubusercontent.com/15264315/54543821-b6989e00-4974-11e9-8c30-11d9e283dd6f.JPG)

**Comment by d4mation** [comment]
Ah, I see what happened here. Somehow, some styling was only applying properly on the "Small Version" but not on the "Large Version". The "Small Version" is actually how it is supposed to look.

I just pushed this fix to Staging. Let me know if it looks as expected 👍

**Comment by banksashleym** [comment]
This looks good too! Thanks!

**Comment by d4mation** [comment]
This change is now Live 👍
