### ISSUE TITLE
4. Not able to sort FAQ's

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#313]
When I'm in the FAQ tab, I am able to click the "sorting" button and then drag the FAQ's around. But when I click on "save sorting" I get a page that says "This site can't be reached. www.jccmi.edu. unexpectedly closed the connection.

Thanks!

**Comment by d4mation** [comment]
@banksashleym 

I've changed up how this works a little on the backend, but things are working correctly now.

Instead of clicking a "Sort" button before sorting, you can just drag-and-drop the items directly.

If you need to adjust how many show per-page, you can do so under the "Screen Options" pane.

![image](https://user-images.githubusercontent.com/7770631/100109025-6b1cdf80-2e39-11eb-8737-6adcc2e6701a.png)

**Comment by d4mation** [comment]
Alternatively, for a more "compact view" you can click the "Re-order" button here: 
![image](https://user-images.githubusercontent.com/7770631/100109323-b9ca7980-2e39-11eb-99e5-fb78b5e36516.png)

**Comment by banksashleym** [comment]
Awesome, thanks so much! So, not to make more work, but is it possible to click on a topic and then be able to drag and drop the FAQ's in a specific topic as well? I have been finding that the more FAQ's I add I have been having to drag a FAQ all the way to the bottom of the list. Thanks!
